### ISSUE TITLE
Municipality total is 0 

### ISSUE THREAD

**Issue by derickvds** [Cale-Torino/Load_shedding_api#1]
Hi,

Do you maybe know why a lot of the suburb "tot" counts are = 0?
If so do you have a workaround to get the selected suburb schedule?

Kind Regards,
Derick

**Comment by Cale-Torino** [comment]
Hi, It looks like when the *Tot* value is *0* that particular suburb will give an invalid response.
I suppose it's an error on Eskom's side so not much I can do. Not very user friendly but hey its Eskom😬.
Perhaps you can try different suburb names sometimes they change these names to make our lives harder.

Example _JSON_ below:

![api](https://user-images.githubusercontent.com/52330180/210149112-40bea5d5-868e-4204-af4d-b7107a601439.jpg)



![apir](https://user-images.githubusercontent.com/52330180/210149076-48e1969b-9001-4e22-b95d-b38edbe878b7.jpg)

**Comment by derickvds** [comment]
Hi,

Thanks for the reply. I thought the issue was on their side. :)

**Comment by Cale-Torino** [comment]
Closed
