### ISSUE TITLE
CoCT

### ISSUE THREAD

**Issue by cnever** [Cale-Torino/Load_shedding_api#2]
How do you get the same data for Capetown? 
Is there any information on this?

Thanks

**Comment by Cale-Torino** [comment]
You should be able to use:
```
https://loadshedding.eskom.co.za/LoadShedding/GetMunicipalities/?Id=9
```
And get started from the municipalities returned. Last time I checked the endpoints did work for Cape Town/somerset west but now there's a new recent issue... the `https://loadshedding.eskom.co.za` domain no longer works reliably and gives `The requested URL was rejected. Please consult with your administrator.` every once and a while... which is a pain...

<img width="360" alt="image" src="https://user-images.githubusercontent.com/52330180/224833857-64398e9f-7333-41e7-acee-3871d2a64fd2.png">

An easier solution for the average person is to use the [ESP API](https://github.com/Cale-Torino/Leveraging_The_EskomSePush_Business_API) If you are not a business you can get a free token on a monthly plan and 50 requests per day.

However I will implore you to take into consideration that ESP also gets some data from the `https://loadshedding.eskom.co.za` so data may be inaccurate at times.
